"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.DataType = void 0;
var DataType;
(function (DataType) {
    DataType[DataType["INT32"] = 0] = "INT32";
    DataType[DataType["BOOL"] = 1] = "BOOL";
    DataType[DataType["INT4"] = 2] = "INT4";
    DataType[DataType["UINT4"] = 3] = "UINT4";
    DataType[DataType["INT8"] = 4] = "INT8";
    DataType[DataType["UINT8"] = 5] = "UINT8";
    DataType[DataType["INT16"] = 6] = "INT16";
    DataType[DataType["UINT16"] = 7] = "UINT16";
    DataType[DataType["FP16"] = 8] = "FP16";
    DataType[DataType["FP32"] = 9] = "FP32";
    DataType[DataType["QSYMMEINT4"] = 10] = "QSYMMEINT4";
    DataType[DataType["QSYMMEINT8"] = 11] = "QSYMMEINT8";
    DataType[DataType["QASYMMEUINT4"] = 12] = "QASYMMEUINT4";
    DataType[DataType["QASYMMEUINT8"] = 13] = "QASYMMEUINT8";
    DataType[DataType["UINT32"] = 14] = "UINT32";
    DataType[DataType["CHAR"] = 15] = "CHAR";
})(DataType = exports.DataType || (exports.DataType = {}));
