"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.TensorType = void 0;
var TensorType;
(function (TensorType) {
    TensorType[TensorType["CONST"] = 0] = "CONST";
    TensorType[TensorType["DYNAMIC"] = 1] = "DYNAMIC";
})(TensorType = exports.TensorType || (exports.TensorType = {}));
