// automatically generated by the FlatBuffers compiler, do not modify

export enum DataType{
  INT32 = 0,
  BOOL = 1,
  INT4 = 2,
  UINT4 = 3,
  INT8 = 4,
  UINT8 = 5,
  INT16 = 6,
  UINT16 = 7,
  FP16 = 8,
  FP32 = 9,
  QSYMMEINT4 = 10,
  QSYMMEINT8 = 11,
  QASYMMEUINT4 = 12,
  QASYMMEUINT8 = 13,
  UINT32 = 14,
  CHAR = 15
}

