"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.DataLayout = void 0;
var DataLayout;
(function (DataLayout) {
    DataLayout[DataLayout["NCHW"] = 0] = "NCHW";
    DataLayout[DataLayout["NHWC"] = 1] = "NHWC";
    DataLayout[DataLayout["ND"] = 2] = "ND";
    DataLayout[DataLayout["NCD"] = 3] = "NCD";
})(DataLayout = exports.DataLayout || (exports.DataLayout = {}));
