"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.ByteBuffer = exports.Builder = exports.Encoding = exports.createLong = exports.Long = exports.isLittleEndian = exports.float64 = exports.float32 = exports.int32 = exports.SIZE_PREFIX_LENGTH = exports.FILE_IDENTIFIER_LENGTH = exports.SIZEOF_INT = exports.SIZEOF_SHORT = void 0;
var constants_1 = require("./constants");
__createBinding(exports, constants_1, "SIZEOF_SHORT");
var constants_2 = require("./constants");
__createBinding(exports, constants_2, "SIZEOF_INT");
var constants_3 = require("./constants");
__createBinding(exports, constants_3, "FILE_IDENTIFIER_LENGTH");
var constants_4 = require("./constants");
__createBinding(exports, constants_4, "SIZE_PREFIX_LENGTH");
var utils_1 = require("./utils");
__createBinding(exports, utils_1, "int32");
__createBinding(exports, utils_1, "float32");
__createBinding(exports, utils_1, "float64");
__createBinding(exports, utils_1, "isLittleEndian");
var long_1 = require("./long");
__createBinding(exports, long_1, "Long");
__createBinding(exports, long_1, "createLong");
var encoding_1 = require("./encoding");
__createBinding(exports, encoding_1, "Encoding");
var builder_1 = require("./builder");
__createBinding(exports, builder_1, "Builder");
var byte_buffer_1 = require("./byte-buffer");
__createBinding(exports, byte_buffer_1, "ByteBuffer");
